### ISSUE TITLE
Error message when sending data

### ISSUE THREAD

**Issue by cfoster0** [sabrinathai/ExperienceSampler#1]
When it gets to the saveDataLastPage script, instead of sending the data to the url, it is going to the error message.

**Comment by squeekur** [comment]
I added these lines to the config.xml and it solved my similar problem.

```
<!--added to fix error -->
<!-- Allow links to example.com-->
<allow-navigation href="http://example.com/*" />
<!-- Wildcards are allowed for the protocol, as a prefix to the host, or as a suffix to the path -->
<allow-navigation href="*://*.http://example.com/*" />
```

https://github.com/apache/cordova-plugin-whitelist

**Comment by cfoster0** [comment]
Hmm. I just tried adding those and it's still giving an error.

**Comment by page-gould** [comment]
Thank you for the help, squeekur! I definitely appreciate you posting the solution.

I am sorry that you are having trouble, cfoster0. The error message is generated when your app is unable to connect to the server where you plan to store the data. This could be caused because you have not set up your data server yet or it is not prepared to receive and process AJAX requests. For participants, they will see this error message when they are not connected to the Internet, but that seems unlikely to be the cause of your problem during development.

In general, though, it is hard to know the source of the problem you are having without more context. Foremost, are you working on an iOS or Android version? Have you set up a data server? It would be most helpful if you could share the code that you have customized. Thank you!

**Comment by cfoster0** [comment]
Hello!

My apologies for not clarifying my situation.

Our lab had been working on an earlier version of the experience sampler code and had successfully set up a Google Sheet for data colelction that was working for both iOS and Android devices. We found this newer version and started to move towards a version based on it over the past month. However, over at least the past 2 weeks, none of our AJAX requests have been working. The code I've been working based on is here: https://github.com/cfoster0/ExperienceSampler/tree/master/Example%20ExperienceSampler/experienceSamplerIOS

I was tracing through the execution of the code and everything else is working properly up until the AJAX request.

Any insight you might have would be tremendously appreciated!

**Comment by sabrinathai** [comment]
Hi cfoster.

In the new version of ExperienceSampler, you will see that in the index.html file, there is a tag called "Content-Security-Policy". In this tag, you will have to specify the url of your server so that the app knows that you have given the Google server permission to access the data from the app. 

To do this, you should take the url of your Google data collector, which is this
**https://script.google.com/macros/s/AKfycbzvFA95fMRUf5HYCSNO1IzEXJ2mYwKGX5Wezx_7MAwNkZ_wozpM/exec**

And then update the Content-Security-Policy tag to be
**meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' data: gap: https://ssl.gstatic.com; style-src 'self' 'unsafe-inline'; media-src *; connect-src https://script.google.com/macros/s/AKfycbzvFA95fMRUf5HYCSNO1IzEXJ2mYwKGX5Wezx_7MAwNkZ_wozpM/exec https://script.googleusercontent.com/macros/echo"**

Currently, the url for the example version of ExperienceSampler is set to our example Google data collector.

That should fix your error message problem.

**Comment by cfoster0** [comment]
Thank you so much! That worked for me.
