### ISSUE TITLE
Data not saving after survey completion

### ISSUE THREAD

**Issue by ashleycov** [sabrinathai/ExperienceSampler#25]
Hi there,

I have spent a week trying to get everything working, but I'm still stuck on the Google option of saving the data. I'm pretty sure I've followed the tutorials correctly. I have the main Google app script, I have the compliance script, I have the three spreadsheets (compliance, splicedDataSet, database) and should have the .js file written as expected. 

I've managed to narrow down the issue to the 'saveDataLastPage' function. I've added the URL of my google app script, but whenever I complete the survey, I don't get the end messages:
`$("#question").html("<h3>Your responses have been recorded. Thank you for completing this survey.</h3>");`

As well, my compliance checker script is sending me emails every night saying this:
`TypeError: Cannot read property "4" from undefined. (line 39, file "Code")`

Line 39 is in the endOfDataCollectionPeriod:
`var endOfDataCollection = new Date(values[4]).getTime();`

I can only imagine this error is coming from the fact that I have no data being collected in my spreadsheets. 

What would help me out is an idea of how to debug an issue inside the ajax call of the 'saveDataLastPage' function or how to debug the Google app script. I've tried putting 'logging' calls, but it's not working. I'm currently loading the apk file onto my Samsung Galaxy S7 phone to test it out. 

Everything else is working as expected (e.g., scheduling, notifications, question ordering), but the data is not getting sent to the spreadsheets properly. 

Let me know if you'd like me to add certain pieces of my code to this thread. 

Thanks!

**Comment by ashleycov** [comment]
I'm happy to have a screen-sharing session over WebEx if someone is available.

**Comment by sabrinathai** [comment]
Hello! 

You are correct. The error you are getting for your Google Script is because there is no data. 
Can you attach the index.js file and the link for one of your google spreadsheets that is used to record data?

**Comment by ashleycov** [comment]
Hi!

Thanks for the response. I'm sorry I managed to missed the notification until now. I've tried a bunch more things, but still pretty much sitting in the same spot. Attached is my index.js file zipped up
[indexjszip.zip](https://github.com/sabrinathai/ExperienceSampler/files/1769900/indexjszip.zip)
. Here is the link to my spreadsheet for collecting the data: https://docs.google.com/spreadsheets/d/17Q05cuzQflteSg6jasDP1DstHl1GUAB_Rg1eVP58lIU/edit#gid=0

One potential unknown is how exactly I input the spreadsheet ID's into the Google App Script. Right now I'm putting "17Q05cuzQflteSg6jasDP1DstHl1GUAB_Rg1eVP58lIU" for the above sheet. Should it be "https://docs.google.com/spreadsheets/d/17Q05cuzQflteSg6jasDP1DstHl1GUAB_Rg1eVP58lIU" instead?

**Comment by ashleycov** [comment]
Hi Sabrina!

I have been working at this pretty hard since my last message. I've been able to narrow down a couple of things:
1) I can get it to a point where if I run the apk in the genymotion emulator, it will write to the database correctly.
2) When I run the exact same apk from 1) on my actual android phone, it does not write to the database correctly. 
3) From the emulator, when I am debugging through the chrome://inspect method, I can see that the Network 'Initiator' is 'https://script....' (see screenshot below for context)
4) From the phone, when I am debugging through the chrome://inspect method, I can see that the Network 'Initiator' is 'exec' - which, when hovering over, evaluates to an https://script...
5) This is the most important.

When I go to my Google App Script and return 'e' at the very top, it evaluates to:

From the phone: 
`{"result":"error","error":{"parameter":{"[object Storage]":""},"contextPath":"","contentLength":16,"queryString":"","parameters":{"[object Storage]":[""]},"postData":{"type":"application/x-www-form-urlencoded","length":16,"contents":"[object Storage]","name":"postData"}}}`

From the emulator: 
`{"result":"error","error":{"parameter":{"1520134048990_startTime_2018_2_3_22_27_28_990":"1","pause_time":"0","participant_id":"5421","uniqueKey":"1520134048990","snoozed":"0","1520134048990.completed_completedSurvey_2018_2_3_22_28_5_144":"1","1520134048990_question2_2018_2_3_22_28_5_138":"2","1520134048990_question_2018_2_3_22_28_1_409":"1"},"contextPath":"","contentLength":270,"queryString":"","parameters":{"1520134048990_startTime_2018_2_3_22_27_28_990":["1"],"pause_time":["0"],"participant_id":["5421"],"uniqueKey":["1520134048990"],"snoozed":["0"],"1520134048990.completed_completedSurvey_2018_2_3_22_28_5_144":["1"],"1520134048990_question2_2018_2_3_22_28_5_138":["2"],"1520134048990_question_2018_2_3_22_28_1_409":["1"]},"postData":{"type":"application/x-www-form-urlencoded","length":270,"contents":"1520134048990.completed_completedSurvey_2018_2_3_22_28_5_144=1&1520134048990_question2_2018_2_3_22_28_5_138=2&1520134048990_question_2018_2_3_22_28_1_409=1&1520134048990_startTime_2018_2_3_22_27_28_990=1&participant_id=5421&pause_time=0&snoozed=0&uniqueKey=1520134048990","name":"postData"}}}`

As you can see, my phone is returning just the '[object Storage]'. 

Do you know why the emulator is returning the parameters and my phone is returning the object?
Do I need to use a release build if I'm going to use my phone, or should the debug build still work on my phone?

I've tried sending localStore.valueOf() and other things in my ajax command, but haven't been able to get the phone to return the right thing. 

This is quite an urgent project that I need to get working soon. Any help/guidance would be much appreciated!

Thanks!
![comparison cordova exec vs https](https://user-images.githubusercontent.com/36122764/36941911-bbda4dce-1f2b-11e8-85ff-b2541d4ea2a0.PNG)

**Comment by frankgasking** [comment]
It might be a separate issue, and i'm going to investigate more tomorrow - but i've just got to the exact same point where i've got the data saving correctly via Genymotion, but not on actual mobile devices once deployed.    

Downloading the key signed APK to my Android phone (with secure app source turned off etc),  the experiment part works fine - but it freezes on the "Saving data to server - please wait message"  and just sits there doing nothing.   It should time out I believe if it cannot communicate with the server after 30 seconds, and update the message - but it doesn't.  So something must be erroring in the background elsewhere - maybe related to ashleycov's issue spotted with the data trying to be sent.

One of the main differences to ashleycov's index.js is that mine is set to "get" and not "post" when calling doing the ajax calls, so i'll try changing that to the same tomorrow to see if there is any difference.   

If I find anything useful out tomorrow, i'll post back here.

**Comment by frankgasking** [comment]
No joy - updated the Google script to the getPost version and it still hangs.    Even changing over to the web server CGI solution will just hang on the message "Thank you for installing our app.  Please wait while the data is sent to our servers".   But it all works fine via the emulator.

Still digging, but it seems there is an issue with the Ajax call - like it's blocking or similar?   I've tried updating the Android manifest file, and all the same results.    So unfortunately we cannot use the ExperienceSampler app at all until we find a resolution.

EDIT - Seems to be around the whole Cordova Whitelist plugin and security settings.  Been playing with different settings in the AndroidManifest.xm and config.xml files on and off in the spare few minutes i've been getting.   Trying some other things today, including trying to fix to the same Cordova plugin versions as in the example script.  Again, will report back if I find anything that works.

**Comment by frankgasking** [comment]
Got it!   Not sure why, but we had to convert the localStore to a string, then into a JSON object for it to work.

So on the data: part of the ajax calls, its now:

data: JSON.parse(JSON.stringify(localStore)),

Not sure why this has to be done, as the emulator doesn't require it.  But its working for us anyway for now.

**Comment by ashleycov** [comment]
Hey @frankgasking 

I was able to figure this out a week ago too, but I've been out of the country since then. I had to do the same thing you did, which worked.

My problem now, is that when I launch 'cordova build android' or 'cordova run android' I get a bunch of errors:
`The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.`
and 
`Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.`
Then near the bottom where it says, 'What went wrong':
`Execution failed for task ':app:processDebugResources'.`

I've looked online at a bunch of similar questions, but not sure which answer is the right one and I don't have much time to fix this. Nothing was manually changed and when I got back this week, this was happening!

Someone please help!

**Comment by frankgasking** [comment]
Yeah, I wasted a bit of time over complicating it, thinking it was the whitelist plugin  ;-)

Usually I had similar issues when Cordova/Maven decided to update when doing a new build in a particular project.  There might be a more efficient way, but I ended up fixing Cordova to the latest version, then the Cordova Android to 6.2.1.  Then created a new project and copied over the WWW folder and compilation was then fine again.

**Comment by bizerkmaverick** [comment]
Good afternoon all,

I'm experiencing the same issues as Ashley when trying to use the compliance script. I'm getting the same error for line 39 of my code:
> TypeError: Cannot read property "4" from undefined. (line 39, file "Code")

`var endOfDataCollection = new Date(values[4]).getTime();`
I'm also getting similar errors for all the other functions throughout my script as follows:

No errors in findCell function.

**findNextEmptyColumn:**

> TypeError: Cannot read property "length" from undefined. (line 25, file "Code")

`for (var j = 5; j < values.length; j++) {`

**endOfDataCollectionPeriod:**

> TypeError: Cannot read property "4" from undefined. (line 39, file "Code")

`var endOfDataCollection = new Date(values[4]).getTime();`

**startOfDataCollectionPeriod:**

> TypeError: Cannot read property "3" from undefined. (line 47, file "Code")

`var startOfDataCollection = new Date(values[3]).getTime();`

**checkCompleted Surveys:**

> TypeError: Cannot read property "4" from undefined. (line 39, file "Code")

`var endOfDataCollection = new Date(values[4]).getTime();`

**spliceData:**

> TypeError: Cannot read property "4" from undefined. (line 39, file "Code")

`var endOfDataCollection = new Date(values[4]).getTime();`

And all functions after give an error as well. Ashley mentioned they thought these errors were because no data was being collected in the spreadsheet. Is there any way to remedy this? The only changes I made to the compliance script that is on github is adding the compliance and splice data strings for my respective google sheets. However, I don't think that is the issue since those same strings are in my saving data google script and seem to be functioning correctly. Data is being recorded in the database spreadsheet from the savedata script as well as the date range appearing in the compliance sheet and the data is organized in the spliced data sheet. However, I can attach my script if needed. Also if needed, I can send a link to my google sheets for the database, compliance, and splice data.

I have attached a zip of my js and html files and the downloaded the compliance google sheet as a csv so the format can be seen.

Let me know if anything else is needed or if I can provide any further clarification.
Thanks,
Erick

[4.17.18.zip](https://github.com/sabrinathai/ExperienceSampler/files/1921341/4.17.18.zip)

**Comment by sabrinathai** [comment]
Hi Everyone,

I think I have a solution but I'm not sure it if this is the right solution this problem. Just to confirm that this is the correct solution, does the Android version of the app hang on the last page message that says it is sending the data to the server and never advances to the success message? 

If that is the problem you are experiencing this is the solution.
Ashley, I hope it's okay if I use your code.

The problem is that the Google server is taking too long to respond to the post request. So you need to implement a timeout feature in the `saveDataLastPage` function:
```
saveDataLastPage:function() {
	var storage=JSON.stringify(localStore);
	var storage_save=JSON.parse(storage);	
     $.ajax({
            type: 'post', //other one was 'get'
            url: 'https://script.google.com/macros/s/AKfycbz_llDo1qmAtYhNCVpMzN8IQ9NItP1KDfhzneX-lQpNKpEttj9V/exec',
            data: storage_save,
            crossDomain: true,
// 	    timeout: 10,
 	    timeout: 120000,            
            success: function (result) {
            var pid = localStore.participant_id, snoozed = localStore.snoozed, uniqueKey = localStore.uniqueKey, pause_time=localStore.pause_time;
            localStore.clear();
            localStore.participant_id = pid;
            localStore.snoozed = snoozed;
			localStore.uniqueKey = uniqueKey;
			localStore.pause_time=pause_time;
            $("#question").html("<h3>Your responses have been recorded. Thank you for completing this survey.</h3>");
            },
			error: function (request, error, textstatus) {
           		if (textstatus === "timeout"){
					$("#question").html("<h3>It looks like the server is currently overloaded. Please try resending your data later. Click on the button below, and we'll remind you in 30 minutes to try sending your data again. If problems persist, please contact the researchers (anc488@mail.usask.ca).</h3><br><button>Set Data Sending Reminder</button>");
					$("#question button").click(function () {app.dataSendingNotif();localStore.snoozed=4;console.log("localStore.snoozed is " + localStore.snoozed);});    

           		}
           		else {
					console.log(error);
               		$("#question").html("<h3>Please try resending data. If problems persist, please contact the researchers (anc488@mail.usask.ca).</h3><br><button>Resend data</button>");
                	$("#question button").click(function () {app.saveDataLastPage();});    
                	}
			}              
            });
},
```
You can uncomment the `timeout: 10,` line to test whether the timeout feature is working correctly. 

You can then implement the set data sending reminder function so participants can set a reminder to resend their data.

At the end of the script, add the following function:
```
dataSendingNotif:function() {
    var now = new Date().getTime(), resendDataDate = new Date(now + 1800*1000);
    var id = '96';
    cordova.plugins.notification.local.schedule({
    					id: id, 
    					title: 'Daily Diaries', 
    					text: 'Please try resending your data now!', 
    					at: resendDataDate, 
    					icon: 'ic_launcher'});
},
```
Make sure this is preceded by a **`},`**

In `surveyQuestions`, add the following question to the end of your questions:
```
                       {
                       "type":"instructions",
                       "variableName":"resendData",
                       "questionPrompt":"Thank you for trying to resend your data.",                       
                       },
```
In `lastPage`, add the following last page message:
```
                {
                "message": "Thank you for trying to resend your data. Please wait while the data is sent to our servers..."
                }
```
In `init`, add the following after the `if (localStore.participant_id === " " || !localStore.participant_id || localStore.participant_id == "undefined") {app.renderQuestion(-NUMSETUPQS);}  ` statement:
```
       else if (localStore.snoozed == 4){
		//update this question number depending on the question index of the question
		app.renderQuestion(3);
	}	
```
In `sampleParticipant`, add 
```
    else if (localStore.snoozed == 4){
		//update this question number
		app.renderQuestion(3);
		localStore.snoozed=0;
	}
```
after this block of code: 
```
if ((current_time - localStore.pause_time) > 600000) { //|| localStore.snoozed == 1) {
        uniqueKey = new Date().getTime();
        localStore.snoozed = 0;
    	var startTime = new Date(uniqueKey);
    	var syear = startTime.getFullYear(), smonth = startTime.getMonth(), sday=startTime.getDate(), shours=startTime.getHours(), sminutes=startTime.getMinutes(), sseconds=startTime.getSeconds(), smilliseconds=startTime.getMilliseconds();
    	localStore[uniqueKey + "_" + "startTime"  + "_" + syear + "_" + smonth + "_" + sday + "_" + shours + "_" + sminutes + "_" + sseconds + "_" + smilliseconds] = 1;	   	    
        app.renderQuestion(0);
    }
```
Finally, add the following lines in `recordResponse`:
```
// you need an if else statement for the last REAL question in your survey that redirects to the end of your survey message
else if (count == 2) {app.renderLastPage(lastPage[2], count);}
// this resendData instruction question is only shown if the participant has been asked to resend data
else if (count == 3) {app.renderLastPage(lastPage[2], count);}    
```

Ashley, I've attached a zip file your www folder that you sent me, but I set the app to write to my own Google Server because I didn't have access to your Google Spreadsheets, so I couldn't see whether the data was being written correctly. 
[www.zip](https://github.com/sabrinathai/ExperienceSampler/files/1925420/www.zip)

I hope this solution resolves the problem you've been facing.
