### ISSUE TITLE
Issues With Compliance Script

### ISSUE THREAD

**Issue by bizerkmaverick** [sabrinathai/ExperienceSampler#26]
Good evening,

I posted a similar comment in the issue posted by aashleycov, but I believe my issue is separate from theirs and so I've made a new issue. I'm experiencing issues when trying to use the compliance script. My data seems to be saving correctly (unique IDs seemed to be generated, the completed tag is generated when a survey is finished, responses to questions seem to appear as the correct text and numbers) in the database google sheet but not in the compliance sheet. The sheet is left completely blank regardless of how many surveys are answered each day. All that seems to appear in compliance sheet is the participant ID, the day it was install and the 2 days after the data collection period. In the compliance google script I'm getting the same error for line 39 of my code:
`var endOfDataCollection = new Date(values[4]).getTime();`

> TypeError: Cannot read property "4" from undefined. (line 39, file "Code")

And all functions in the compliance script after give an error as well. The only changes I made to the compliance script that is on github is adding the compliance and splice data strings for my respective google sheets. However, I don't think that is the issue since those same strings are in my saving data google script and seem to be functioning correctly. Data is being recorded in the database spreadsheet from the savedata script as well as the date range appearing in the compliance sheet and the data is organized in the spliced data sheet. However, I can attach my script if needed. Also if needed, I can send a link to my google sheets for the database, compliance, and splice data.

I have attached a zip of my js and html files, all the scripts that are being used, and the downloaded copies of all google sheets being used for saving data and compliance. I can provide links to any of the google sheets or scripts if needed as well.

Let me know if anything else is needed or if I can provide any further clarification.
Thanks,
Erick

[4.29.18.zip](https://github.com/sabrinathai/ExperienceSampler/files/1959651/4.29.18.zip)

**Comment by sabrinathai** [comment]
Hi Erick,

In your compliance spreadsheet, do the IDs match the sheet names in the spliced data file? If there is a sheet in the spliced data file that is not in the compliance spreadsheet, you will get that error message.

**Comment by Gryphire** [comment]
Hi Sabrina and Erick,

I'm experiencing the same issue (i.e. TypeError: Cannot read property "4" from undefined. (line 39, file "Code")) and the ID names do not seem to have anything to do with it. 

I have noticed, however, that I've got a couple of uniquekey variables that have the value 'undefined' (as do all of my 'pause_time' variables), so maybe 

TypeError: Cannot read property "4" from undefined. (line 39, file "Code")

is referencing this 'undefined' value?

If this is indeed, the problem, I'm wondering how to solve it. Any ideas?

Also, is there an example splicedDataset as well? I'm not sure my version of that sheet is correct. 

Thanks and cheers,
Nastasia

**EDIT: I figured it out, my problems seem to have been due to the an empty sheet having been created in the database when I first ran the app a long time ago, and I just assumed it was supposed to be there for some reason. Deleting that empty first sheet (had no name either) seems to have solved the issue. However, it would still be great to have an example of the splicedDataset sheet, because mine still doesn't look right (I think), @sabrinathai. Thanks a lot!**
