### ISSUE TITLE
Issues with plugins

### ISSUE THREAD

**Issue by mbloechl05** [sabrinathai/ExperienceSampler#40]
Hi, 

we would like to use ExperienceSampler, because it sounds like an excellent tool! 

However, while building the app for iOS, we ran into issues in the testing stage (iOS; http://www.experiencesampler.com/testing/) we cannot solve. 

We think we did all according to the instructions on the website -- two people tried to set it up independently, one is an experienced coder who has also used Xcode before. But we only get a blank screen with quite a few warnings and errors in Xcode. We think the problems might mainly arise from issues with plugins, which are a bit old and sometimes not supported anymore? 

Anyway, it's really difficult to debug it. Do you have any experience with compiling this with the latest Cordova and Xcode versions? If not, could you please document which versions worked before? 

Any help would be greatly appreciated. 

Thanks, 
Maria

**Comment by page-gould** [comment]
In order to help, we need more information about what issues you are experiencing. Would you please copy and paste the error messages that you are getting and specify where you are getting them?

To be specific, I'm wondering if you are encountering the first problems when you try to build your app using the Cordova Command Line Interface or is that working but you encounter problems when you launch the *.xcodeproj file in Xcode? And then, would you please copy and paste the first error message you get? Thank you!

**Comment by mbloechl05** [comment]
Sure! 

When following the [initial step-by-step instructions](http://www.experiencesampler.com/createapp/), this appears to work fine.

When getting to testing, `cordova build` leads to a number (>50) of deprecation warning most of which seem related to `UILocalNotification` and are marked deprecated "since iOS 9.0" or "since iOS 10.0".

The build then fails with

```
.../platforms/ios/<DISPLAY_NAME>/Plugins/cordova-plugin-app-event/CDVPlugin+APPAppEvent.m:65:23: error: 
    use of undeclared identifier 'CDVLocalNotification'
               name:CDVLocalNotification
```

Invoking the build via Xcode (as described in "iOS Testing" section) leads to the same result.

Versions used:
* cordova 9.0.0
* cordova-ios 5.0.1
* Xcode 10.2.1
* Apple LLVM 10.0.1

I hope this clarifies it?

**Comment by page-gould** [comment]
I think so! Thanks so much for providing all of these details!

OK, my guess is that you got stuck due to installing a specific form of the ios notifications plugin for ios10 that is only needed in some cases -- it is confusing in our documentation, and I apologize for your lost time. My guess is that you installed the notifications plugin that is specific to ios10.

My first guess at the solution would be for you to try rebuilding the project using the normal katzer plugin (i.e., not the one specific to ios10). So, save your customized index.js file and anything else in a new folder, and then build the project anew [(http://experiencesampler.com/createapp/)](http://experiencesampler.com/createapp/) but stopping after you install the normal katzer plugin (i.e., this is your last line for installing plugins: `cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications`). Note that means you are not installing the katzer plugin that ends with #ios10 and is mentioned in the next line of the instructions on our CreateApp page. 

We need to be more specific about when to use the ios10 one, but _not_ using it fixed the same problem for me. After rebuilding the project, copy your customized index.js back into the www/js/ folder and try to build it again. Did that fix it for you?

**Comment by mollymendoza** [comment]
I had the same problem, and the issue was fixed by rebuilding and not adding the iOS specific plugin. Thank you!!! Am I going to run into problems later without this plugin? I guess my question is, in which cases would I need this plugin?

**Comment by page-gould** [comment]
So glad that it worked for you, too! I'm pretty sure the answer is, "No." You actually still installed the plugin (i.e., the one you skipped is the same as the katzer/cordova-plugin-local-notifications, just not specific to iOS10). So, you still have the plugin! Also, I was able to deploy my app without any problems, as almost all devices should be on iOS 12 by now.
