### ISSUE TITLE
Experience Sampler - Build Command Failed 

### ISSUE THREAD

**Issue by e1inda** [sabrinathai/ExperienceSampler#41]
Hi, 

I am attempting to run the experience sampler platform and have reached the step of adding plugins and have recieved this message! 

Wondering if I should go back and re-install or if there is a command I can use to over come this failed command. 
![Screen Shot 2019-05-10 at 2 34 50 pm](https://user-images.githubusercontent.com/50604428/57667494-09c26080-7647-11e9-88e6-d38729922ec6.png)

Thank you in advance

**Comment by sabrinathai** [comment]
Hi e1inda,

Thank you for your interest in ExperienceSampler! I would first try to Google the error message you received to see if there are any potential solutions out there that I am not aware of yet. If there are none, then it is probably easiest to go back and re-install. 

Best,
Sabrina

**Comment by page-gould** [comment]
I might know what caused this and how to fix it, because I'm pretty sure I had the same problem: Try going back and reinstalling, but then stopping after you install the normal katzer plugin (i.e., this is your last line for installing plugins: cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications). Note that means you are not installing the katzer plugin that ends with #ios10 and is mentioned in the next line of the instructions on our CreateApp page.

I am curious if that fixes your problem?

**Comment by e1inda** [comment]
Thank you both for your input! Page-gould your instructions fixed it, thank you again
