### ISSUE TITLE
example app just shows a blue screen

### ISSUE THREAD

**Issue by hakanjonsson** [sabrinathai/ExperienceSampler#8]
I can build an deploy the example app, but if I launch it on an Android phone, it just shows a blue screen.

**Comment by sabrinathai** [comment]
That suggests that there is a syntactical error in the index.js file. You can inspect the errors by following the Android instructions on this page http://experiencesampler.com/testing.html

**Comment by hakanjonsson** [comment]
I was under the impression that the template file would build without problems, but that is not the case. It contains syntax errors as you say. Maybe a good idea to fix it.

**Comment by sabrinathai** [comment]
Actually that is incorrect. You can build the **example** app using the files in the **Example ExperienceSampler** folder, but the template files **must be customized first** before you can build it. The cause of the syntactical error is this section of the template file:
` {
"type":"question type","variableName": "variableName","questionPrompt": "Exact question wording","minResponse": /*minimum numerical value of the scale or multiple choice option*/,
"maxResponse": /*maximum numerical value of the scale or multiple choice option*/, "labels": [
{"label": "label for minimum numerical value of scale or first option for multiple choice question"},
{"label": "label for maximum numerical value of scale or second option for multiple choice question"}
],
},
`
Specifically, it is this line of code `"minResponse": /*minimum numerical value of the scale or multiple choice option*/,` because we have included instructions in comments instead of the minimum numerical value of the scale. You see a blue screen because this results in a syntactical error of an unexpected comma (i.e., comma should not follow a comment); however, once you replace the comment with the minimum numerical value, the comma is correct. This will be true of numerous lines of code in the template file. We did this to help novice programmers identify where to input values and what to input when they are customizing the template files. Therefore, you will always encounter a blue screen if you build from the template files **BEFORE** customizing. 

If you want to be certain that the app will build after you customize it, you can always build the example version that we have first, and then adjust the example app to suit your research project.
